version: '3'

services:
  http:
    build:
      context: ./infrastructure/docker/nginx
    env_file:
      - ./infrastructure/environments/development.env
    ports:
      - "8000:80"
    volumes:
      - ./infrastructure/docker/http.conf:/etc/nginx/conf.d/default.conf
      - ./src:/code
    depends_on:
      - php

  php:
    build:
      context: ./infrastructure/docker/php
    env_file:
      - ./infrastructure/environments/development.env
    volumes:
      - ./src:/code
    depends_on:
      - dbmysql
  
  dbmysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3300:3306    
    volumes:
      - ./data/db/:/var/lib/mysql
    env_file:
      - ./infrastructure/environments/development.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080 

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
