version: '3'

services:
  http:
    build:
      context: ./infrastructure/docker/nginx
    env_file:
      - ./infrastructure/environments/development.env
    ports:
      - "8000:80"
    volumes:
      - ./infrastructure/docker/http.conf:/etc/nginx/conf.d/default.conf
      - ./src:/code
    depends_on:
      - php

  php:
    build:
      context: ./infrastructure/docker/php
    env_file:
      - ./infrastructure/environments/development.env
    volumes:
      - ./src:/code
    depends_on:
      - db

  
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3300:3306    
    volumes:
      - ./data/db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080 
