doctrine:
    dbal:
        dbname:               '%env(MYSQL_DATABASE)%'
        host:                 dbmysql
        port:                 3306
        user:                 '%env(MYSQL_USER)%'
        password:             '%env(MYSQL_PASSWORD)%'
        driver:               pdo_mysql

        server_version:       '5.7'

        #url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Authentication:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Bundle/Api/Persistence/Migrations/Authentication'
                prefix: 'LetEmTalk\Component\Domain\Authentication'
                alias: Authentication
            Authorization:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Bundle/Api/Persistence/Migrations/Authorization'
                prefix: 'LetEmTalk\Component\Domain\Authorization'
                alias: Authorization
            Chat:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Bundle/Api/Persistence/Migrations/Chat'
                prefix: 'LetEmTalk\Component\Domain\Chat'
                alias: Chat
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Bundle/Api/Persistence/Migrations/User'
                prefix: 'LetEmTalk\Component\Domain\User'
                alias: User


