#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_create_user:
  path: /api/user/
  controller: 'LetEmTalk\Bundle\Api\Controller\User\CreateUserController::execute'
  methods: POST

api_read_users:
  path: /api/users/
  controller: 'LetEmTalk\Bundle\Api\Controller\User\ReadUsersController::execute'
  methods: GET

api_delete_user:
  path: /api/user/{id}/
  controller: 'LetEmTalk\Bundle\Api\Controller\User\DeleteUserController:execute'
  methods: DELETE

login:
  path: /login/
  controller: 'LetEmTalk\Bundle\Api\Controller\Authentication\SecurityController::login'
  methods: GET|POST

api_create_room:
  path: /api/room/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\CreateRoomController::execute'
  methods: POST

api_read_room:
  path: /api/room/{roomId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\ReadRoomWithIssuesController::execute'
  methods: GET

api_delete_room:
  path: /api/room/{roomId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\DeleteRoomController::execute'
  methods: DELETE

api_create_issue:
  path: /api/issue/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\CreateIssueController::execute'
  methods: POST

api_read_issue:
  path: /api/issue/{issueId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\ReadIssueWithPillsController::execute'
  methods: GET

api_update_issue:
  path: /api/issue/{issueId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\UpdateIssueController::execute'
  methods: PUT

api_delete_issue:
  path: /api/issue/{issueId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\DeleteIssueController::execute'
  methods: DELETE

api_create_pill:
  path: /api/pill/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\CreatePillController::execute'
  methods: POST

api_update_pill:
  path: /api/pill/{pillId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\UpdatePillController::execute'
  methods: PUT

api_delete_pill:
  path: /api/pill/{pillId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\DeletePillController::execute'
  methods: DELETE

api_read_roles:
  path: /api/roles/
  controller: 'LetEmTalk\Bundle\Api\Controller\Authorization\ReadRolesController::execute'
  methods: GET

api_create_room_permission:
  path: /api/permission/room/
  controller: 'LetEmTalk\Bundle\Api\Controller\Authorization\CreateUserToRoomPermissionController::execute'
  methods: POST

api_delete_room_permission:
  path: /api/permission/room/{userId}/{roomId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Authorization\DeleteUserToRoomPermissionController::execute'
  methods: DELETE

api_create_issue_permission:
  path: /api/permission/issue/
  controller: 'LetEmTalk\Bundle\Api\Controller\Authorization\CreateUserToIssuePermissionController::execute'
  methods: POST

api_delete_issue_permission:
  path: /permission/issue/{userId}/{issueId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Authorization\DeleteUserToIssuePermissionController::execute'
  methods: DELETE
