#index:
#    path: /
#    controller: App\Controller\DefaultController::index

create_user:
  path: /user/
  controller: 'App\Bundle\ApiLet\Controller\User\CreateUserController::execute'
  methods: POST

read_users:
  path: /users/
  controller: 'App\Bundle\ApiLet\Controller\User\ReadUsersController::execute'
  methods: GET

delete_user:
  path: /user/{id}/
  controller: 'App\Bundle\ApiLet\Controller\User\DeleteUserController:execute'
  methods: DELETE
