#index:
#    path: /
#    controller: App\Controller\DefaultController::index

create_user:
  path: /user/
  controller: 'LetEmTalk\Bundle\Api\Controller\User\CreateUserController::execute'
  methods: POST

read_users:
  path: /users/
  controller: 'LetEmTalk\Bundle\Api\Controller\User\ReadUsersController::execute'
  methods: GET

delete_user:
  path: /user/{id}/
  controller: 'LetEmTalk\Bundle\Api\Controller\User\DeleteUserController:execute'
  methods: DELETE

login:
  path: /login/
  controller: 'LetEmTalk\Bundle\Api\Controller\Authentication\SecurityController::login'
  methods: GET|POST

create_room:
  path: /room/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\CreateRoomController::execute'
  methods: POST

read_room:
  path: /room/{roomId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\ReadRoomWithIssuesController::execute'
  methods: GET

delete_room:
  path: /room/{roomId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\DeleteRoomController::execute'
  methods: DELETE

create_issue:
  path: /issue/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\CreateIssueController::execute'
  methods: POST

read_issue:
  path: /issue/{issueId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\ReadIssueWithPillsController::execute'
  methods: GET

update_issue:
  path: /issue/{issueId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\UpdateIssueController::execute'
  methods: POST

delete_issue:
  path: /issue/{issueId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\DeleteIssueController::execute'
  methods: DELETE

create_pill:
  path: /pill/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\CreatePillController::execute'
  methods: POST

update_pill:
  path: /pill/{pillId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\UpdatePillController::execute'
  methods: POST

delete_pill:
  path: /pill/{pillId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Chat\DeletePillController::execute'
  methods: DELETE

read_roles:
  path: /roles/
  controller: 'LetEmTalk\Bundle\Api\Controller\Authorization\ReadRolesController::execute'
  methods: GET

create_room_permission:
  path: /permission/room/
  controller: 'LetEmTalk\Bundle\Api\Controller\Authorization\CreateUserToRoomPermissionController::execute'
  methods: POST

delete_room_permission:
  path: /permission/room/{userId}/{roomId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Authorization\DeleteUserToRoomPermissionController::execute'
  methods: DELETE

create_issue_permission:
  path: /permission/issue/
  controller: 'LetEmTalk\Bundle\Api\Controller\Authorization\CreateUserToIssuePermissionController::execute'
  methods: POST

delete_issue_permission:
  path: /permission/issue/{userId}/{issueId}/
  controller: 'LetEmTalk\Bundle\Api\Controller\Authorization\DeleteUserToIssuePermissionController::execute'
  methods: DELETE
