#index:
#    path: /
#    controller: App\Controller\DefaultController::index

create_user:
  path: /user/
  controller: 'App\Bundle\ApiLet\Controller\User\CreateUserController::execute'
  methods: POST
