# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
         autowire: true      # Automatically injects dependencies in your services.
         autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    LetEmTalk\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    #App\Controller\:
    #    resource: '../src/Bundle/ApiLet/Controller/User'
    #    tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    LetEmTalk\Bundle\Api\Controller\User\CreateUserController:
        arguments:
            - '@letemtalk.useCase.createUser'
            - '@letemtalk.useCase.createUserCredentials'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\User\ReadUsersController:
        arguments:
            - '@letemtalk.useCase.readUsers'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\User\DeleteUserController:
        arguments:
            - '@letemtalk.useCase.deleteUser'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\CreateRoomController:
        arguments:
            - '@letemtalk.useCase.createRoom'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\CreateIssueController:
        arguments:
            - '@letemtalk.useCase.createIssue'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\CreatePillController:
        arguments:
            - '@letemtalk.useCase.createPill'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\UpdatePillController:
        arguments:
            - '@letemtalk.useCase.updatePill'
        tags: ['controller.service_arguments']


    letemtalk.metadata.user:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\User\Entity\User ]

    letemtalk.metadata.userCredentials:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\Authentication\Entity\UserCredentials ]

    letemtalk.metadata.room:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\Chat\Entity\Room ]

    letemtalk.metadata.issue:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\Chat\Entity\Issue ]

    letemtalk.metadata.pill:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\Chat\Entity\Pill ]

    letemtalk.repository.user:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\User\DoctrineUserRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.user'

    letemtalk.repository.userCredentials:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Authentication\DoctrineUserCredentialsRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.userCredentials'

    letemtalk.repository.room:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Chat\DoctrineRoomRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.room'

    letemtalk.repository.issue:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Chat\DoctrineIssueRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.issue'

    letemtalk.repository.pill:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Chat\DoctrinePillRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.pill'

    letemtalk.useCase.createUser:
        class: LetEmTalk\Component\Application\User\UseCase\CreateUserUseCase
        arguments:
            - '@letemtalk.repository.user'

    letemtalk.useCase.readUsers:
        class: LetEmTalk\Component\Application\User\UseCase\ReadUsersUseCase
        arguments:
            - '@letemtalk.repository.user'

    letemtalk.useCase.deleteUser:
        class: LetEmTalk\Component\Application\User\UseCase\DeleteUserUseCase
        arguments:
            - '@letemtalk.repository.user'

    letemtalk.useCase.createUserCredentials:
        class: LetEmTalk\Component\ApiLet\Application\Authentication\UserCase\CreateUserCredentialsUseCase
        arguments:
            - '@letemtalk.repository.userCredentials'

    letemtalk.useCase.createRoom:
        class: LetEmTalk\Component\Application\Chat\UseCase\CreateRoomUseCase
        arguments:
            - '@letemtalk.repository.room'
            - '@letemtalk.repository.user'

    letemtalk.useCase.createIssue:
        class: LetEmTalk\Component\Application\Chat\UseCase\CreateIssueUseCase
        arguments:
            - '@letemtalk.repository.issue'
            - '@letemtalk.repository.room'
            - '@letemtalk.repository.pill'
            - '@letemtalk.repository.user'

    letemtalk.useCase.createPill:
        class: LetEmTalk\Component\Application\Chat\UseCase\CreatePillUseCase
        arguments:
            - '@letemtalk.repository.pill'
            - '@letemtalk.repository.issue'
            - '@letemtalk.repository.user'

    letemtalk.useCase.updatePill:
        class: LetEmTalk\Component\Application\Chat\UseCase\UpdatePillUseCase
        arguments:
            - '@letemtalk.repository.pill'
