# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
         autowire: true      # Automatically injects dependencies in your services.
         autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    LetEmTalk\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    #App\Controller\:
    #    resource: '../src/Bundle/ApiLet/Controller/User'
    #    tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    LetEmTalk\Bundle\Api\Controller\User\CreateUserController:
        arguments:
            - '@letemtalk.useCase.createUser'
            - '@letemtalk.useCase.createUserCredentials'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\User\ReadUserController:
        arguments:
            - '@letemtalk.useCase.readUser'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\User\ReadUsersController:
        arguments:
            - '@letemtalk.useCase.readUsers'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\User\DeleteUserController:
        arguments:
            - '@letemtalk.useCase.deleteUser'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\CreateRoomController:
        arguments:
            - '@letemtalk.useCase.createRoom'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\ReadRoomWithIssuesController:
        arguments:
            - '@letemtalk.useCase.readRoomWithIssues'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\ReadRoomsController:
        arguments:
            - '@letemtalk.useCase.readRooms'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\DeleteRoomController:
        arguments:
            - '@letemtalk.useCase.deleteRoom'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\CreateIssueController:
        arguments:
            - '@letemtalk.useCase.createIssue'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\ReadIssueWithPillsController:
        arguments:
            - '@letemtalk.useCase.readIssueWithPills'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\UpdateIssueController:
        arguments:
            - '@letemtalk.useCase.updateIssue'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\DeleteIssueController:
        arguments:
            - '@letemtalk.useCase.deleteIssue'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\CreatePillController:
        arguments:
            - '@letemtalk.useCase.createPill'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\UpdatePillController:
        arguments:
            - '@letemtalk.useCase.updatePill'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Chat\DeletePillController:
        arguments:
            - '@letemtalk.useCase.deletePill'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Authorization\ReadRolesController:
        arguments:
            - '@letemtalk.useCase.readRoles'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Authorization\AssignRoleToUserController:
        arguments:
            - '@letemtalk.useCase.assignRoleToUser'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Authorization\CreateUserToRoomPermissionController:
        arguments:
            - '@letemtalk.useCase.createUserToRoomPermission'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Authorization\DeleteUserToRoomPermissionController:
        arguments:
            - '@letemtalk.useCase.deleteUserToRoomPermission'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Authorization\CreateUserToIssuePermissionController:
        arguments:
            - '@letemtalk.useCase.createUserToIssuePermission'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Authorization\DeleteUserToIssuePermissionController:
        arguments:
            - '@letemtalk.useCase.deleteUserToIssuePermission'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\Authentication\LoginAuthenticator:
        arguments:
            - '@letemtalk.repository.redis.userCredentials'

    letemtalk.metadata.user:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\User\Entity\User ]

    letemtalk.metadata.userCredentials:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\Authentication\Entity\UserCredentials ]

    letemtalk.metadata.room:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\Chat\Entity\Room ]

    letemtalk.metadata.issue:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\Chat\Entity\Issue ]

    letemtalk.metadata.pill:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\Chat\Entity\Pill ]

    letemtalk.metadata.role:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\Authorization\Entity\Role ]

    letemtalk.metadata.userToRoomPermission:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\Authorization\Entity\UserToRoomPermission ]

    letemtalk.metadata.userToIssuePermission:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\Authorization\Entity\UserToIssuePermission ]

    letemtalk.metadata.adminPermission:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\Authorization\Entity\AdminPermission ]

    letemtalk.repository.doctrine.user:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\User\DoctrineUserRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.user'

    letemtalk.repository.redis.user:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\User\RedisUserRepository
        arguments:
            - '@letemtalk.repository.doctrine.user'

    letemtalk.repository.doctrine.userCredentials:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Authentication\DoctrineUserCredentialsRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.userCredentials'

    letemtalk.repository.redis.userCredentials:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Authentication\RedisUserCredentialsRepository
        arguments:
            - '@letemtalk.repository.doctrine.userCredentials'

    letemtalk.repository.doctrine.room:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Chat\DoctrineRoomRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.room'

    letemtalk.repository.redis.room:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Chat\RedisRoomRepository
        arguments:
            - '@letemtalk.repository.doctrine.room'

    letemtalk.repository.doctrine.issue:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Chat\DoctrineIssueRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.issue'

    letemtalk.repository.redis.issue:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Chat\RedisIssueRepository
        arguments:
            - '@letemtalk.repository.doctrine.issue'

    letemtalk.repository.redisInvalidate.issue:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Chat\RedisInvalidateIssueRepository
        arguments:
            - '@letemtalk.repository.doctrine.issue'

    letemtalk.repository.doctrine.pill:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Chat\DoctrinePillRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.pill'

    letemtalk.repository.redis.pill:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Chat\RedisPillRepository
        arguments:
            - '@letemtalk.repository.doctrine.pill'

    letemtalk.repository.redisInvalidate.pill:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Chat\RedisInvalidatePillRepository
        arguments:
            - '@letemtalk.repository.doctrine.pill'

    letemtalk.repository.doctrine.role:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Authorization\DoctrineRoleRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.role'

    letemtalk.repository.redis.role:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Authorization\RedisRoleRepository
        arguments:
            - '@letemtalk.repository.doctrine.role'

    letemtalk.repository.doctrine.userToRoomPermission:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Authorization\DoctrineUserToRoomPermissionRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.userToRoomPermission'

    letemtalk.repository.redis.userToRoomPermission:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Authorization\RedisUserToRoomPermissionRepository
        arguments:
            - '@letemtalk.repository.doctrine.userToRoomPermission'

    letemtalk.repository.doctrine.adminPermission:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Authorization\DoctrineAdminPermissionRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.adminPermission'

    letemtalk.repository.redis.adminPermission:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Authorization\RedisAdminPermissionRepository
        arguments:
            - '@letemtalk.repository.doctrine.adminPermission'

    letemtalk.repository.doctrine.userToIssuePermission:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Authorization\DoctrineUserToIssuePermissionRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.userToIssuePermission'

    letemtalk.repository.redis.userToIssuePermission:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Authorization\RedisUserToIssuePermissionRepository
        arguments:
            - '@letemtalk.repository.doctrine.userToIssuePermission'



    letemtalk.useCase.createUser:
        class: LetEmTalk\Component\Application\User\UseCase\CreateUserUseCase
        arguments:
            - '@letemtalk.repository.redis.user'
            - '@letemtalk.service.adminAuthorization'

    letemtalk.useCase.readUsers:
        class: LetEmTalk\Component\Application\User\UseCase\ReadUsersUseCase
        arguments:
            - '@letemtalk.repository.redis.user'
            - '@letemtalk.service.adminAuthorization'

    letemtalk.useCase.readUser:
        class: LetEmTalk\Component\Application\User\UseCase\ReadUserUseCase
        arguments:
            - '@letemtalk.repository.redis.user'
            - '@letemtalk.service.adminAuthorization'

    letemtalk.useCase.deleteUser:
        class: LetEmTalk\Component\Application\User\UseCase\DeleteUserUseCase
        arguments:
            - '@letemtalk.repository.redis.user'
            - '@letemtalk.service.adminAuthorization'

    letemtalk.useCase.createUserCredentials:
        class: LetEmTalk\Component\Application\Authentication\UseCase\CreateUserCredentialsUseCase
        arguments:
            - '@letemtalk.repository.redis.userCredentials'
            - '@letemtalk.service.adminAuthorization'

    letemtalk.useCase.createRoom:
        class: LetEmTalk\Component\Application\Chat\UseCase\CreateRoomUseCase
        arguments:
            - '@letemtalk.repository.redis.room'
            - '@letemtalk.repository.doctrine.user'
            - '@letemtalk.service.adminAuthorization'

    letemtalk.useCase.readRoomWithIssues:
        class: LetEmTalk\Component\Application\Chat\UseCase\ReadRoomWithIssuesUseCase
        arguments:
            - '@letemtalk.repository.redis.room'
            - '@letemtalk.repository.redis.issue'
            - '@letemtalk.service.userAuthorization'

    letemtalk.useCase.readRooms:
        class: LetEmTalk\Component\Application\Chat\UseCase\ReadRoomsUseCase
        arguments:
            - '@letemtalk.service.userAuthorization'
            - '@letemtalk.service.adminAuthorization'
            - '@letemtalk.repository.redis.room'

    letemtalk.useCase.deleteRoom:
        class: LetEmTalk\Component\Application\Chat\UseCase\DeleteRoomUseCase
        arguments:
            - '@letemtalk.repository.redis.room'
            - '@letemtalk.service.adminAuthorization'

    letemtalk.useCase.createIssue:
        class: LetEmTalk\Component\Application\Chat\UseCase\CreateIssueUseCase
        arguments:
            - '@letemtalk.repository.redis.issue'
            - '@letemtalk.repository.doctrine.room'
            - '@letemtalk.repository.redis.pill'
            - '@letemtalk.repository.doctrine.user'
            - '@letemtalk.service.userAuthorization'
            - '@letemtalk.application.service.createIssuePermission'

    letemtalk.useCase.readIssueWithPills:
        class: LetEmTalk\Component\Application\Chat\UseCase\ReadIssueWithPillsUseCase
        arguments:
            - '@letemtalk.repository.redis.issue'
            - '@letemtalk.repository.redis.pill'
            - '@letemtalk.service.userAuthorization'

    letemtalk.useCase.updateIssue:
        class: LetEmTalk\Component\Application\Chat\UseCase\UpdateIssueUseCase
        arguments:
            - '@letemtalk.repository.redisInvalidate.issue'
            - '@letemtalk.service.userAuthorization'

    letemtalk.useCase.deleteIssue:
        class: LetEmTalk\Component\Application\Chat\UseCase\DeleteIssueUseCase
        arguments:
            - '@letemtalk.repository.redisInvalidate.issue'
            - '@letemtalk.service.userAuthorization'

    letemtalk.useCase.createPill:
        class: LetEmTalk\Component\Application\Chat\UseCase\CreatePillUseCase
        arguments:
            - '@letemtalk.repository.redis.pill'
            - '@letemtalk.repository.doctrine.issue'
            - '@letemtalk.repository.doctrine.user'
            - '@letemtalk.service.userAuthorization'

    letemtalk.useCase.updatePill:
        class: LetEmTalk\Component\Application\Chat\UseCase\UpdatePillUseCase
        arguments:
            - '@letemtalk.repository.redisInvalidate.pill'
            - '@letemtalk.service.userAuthorization'

    letemtalk.useCase.deletePill:
        class: LetEmTalk\Component\Application\Chat\UseCase\DeletePillUseCase
        arguments:
            - '@letemtalk.repository.redisInvalidate.pill'
            - '@letemtalk.service.userAuthorization'

    letemtalk.useCase.readRoles:
        class: LetEmTalk\Component\Application\Authorization\UseCase\ReadRolesUseCase
        arguments:
            - '@letemtalk.repository.redis.role'

    letemtalk.useCase.assignRoleToUser:
        class: LetEmTalk\Component\Application\Authorization\UseCase\AssignRoleToUserUseCase
        arguments:
            - '@letemtalk.repository.doctrine.room'
            - '@letemtalk.repository.doctrine.role'
            - '@letemtalk.repository.doctrine.user'
            - '@letemtalk.repository.redis.userToRoomPermission'
            - '@letemtalk.service.adminAuthorization'

    letemtalk.useCase.createUserToRoomPermission:
        class: LetEmTalk\Component\Application\Authorization\UseCase\CreateUserToRoomPermissionUseCase
        arguments:
            - '@letemtalk.repository.redis.userToRoomPermission'
            - '@letemtalk.repository.doctrine.user'
            - '@letemtalk.repository.doctrine.room'
            - '@letemtalk.repository.doctrine.role'
            - '@letemtalk.service.adminAuthorization'

    letemtalk.useCase.deleteUserToRoomPermission:
        class: LetEmTalk\Component\Application\Authorization\UseCase\DeleteUserToRoomPermissionUseCase
        arguments:
            - '@letemtalk.repository.redis.userToRoomPermission'
            - '@letemtalk.service.adminAuthorization'

    letemtalk.useCase.createUserToIssuePermission:
        class: LetEmTalk\Component\Application\Authorization\UseCase\CreateUserToIssuePermissionUseCase
        arguments:
            - '@letemtalk.repository.redis.userToIssuePermission'
            - '@letemtalk.repository.doctrine.user'
            - '@letemtalk.repository.doctrine.issue'
            - '@letemtalk.repository.redis.role'
            - '@letemtalk.service.adminAuthorization'

    letemtalk.useCase.deleteUserToIssuePermission:
        class: LetEmTalk\Component\Application\Authorization\UseCase\DeleteUserToIssuePermissionUseCase
        arguments:
            - '@letemtalk.repository.redis.userToIssuePermission'
            - '@letemtalk.service.adminAuthorization'

    letemtalk.service.userAuthorization:
        class: LetEmTalk\Component\Domain\Authorization\Service\UserAuthorization
        arguments:
            - '@letemtalk.repository.redis.userToRoomPermission'
            - '@letemtalk.repository.redis.userToIssuePermission'
            - '@letemtalk.repository.redis.user'

    letemtalk.service.adminAuthorization:
        class: LetEmTalk\Component\Domain\Authorization\Service\AdminAuthorization
        arguments:
            - '@letemtalk.repository.redis.adminPermission'
            - '@letemtalk.repository.redis.user'

    letemtalk.application.service.createIssuePermission:
        class: LetEmTalk\Component\Application\Authorization\Service\CreateIssuePermission
        arguments:
            - '@letemtalk.repository.doctrine.userToIssuePermission'
            - '@letemtalk.repository.doctrine.userToRoomPermission'


    letemtalk.event.ResponseHeaders:
        class: LetEmTalk\Bundle\Api\Service\ResponseHeadersListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
