# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
         autowire: true      # Automatically injects dependencies in your services.
         autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    LetEmTalk\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    #App\Controller\:
    #    resource: '../src/Bundle/ApiLet/Controller/User'
    #    tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    LetEmTalk\Bundle\Api\Controller\User\CreateUserController:
        arguments:
            $createUserUseCase: '@letemtalk.usecase.createuser'
            $createUserCredentialsUseCase: '@letemtalk.usercase.createusercredentials'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\User\ReadUsersController:
        arguments:
            $readUsersUseCase: '@letemtalk.usecase.readusers'
        tags: ['controller.service_arguments']

    LetEmTalk\Bundle\Api\Controller\User\DeleteUserController:
        arguments:
            $deleteUserUseCase: '@letemtalk.usecase.deleteuser'
        tags: ['controller.service_arguments']

    letemtalk.metadata.user:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\User\Entity\User ]

    letemtalk.metadata.usercredentials:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [ LetEmTalk\Component\Domain\Authentication\Entity\UserCredentials ]

    letemtalk.repository.user:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\User\DoctrineUserRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.user'

    letemtalk.repository.usercredentials:
        class: LetEmTalk\Bundle\Api\Persistence\Repository\Authentication\DoctrineUserCredentialsRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@letemtalk.metadata.usercredentials'

    letemtalk.usecase.createuser:
        class: LetEmTalk\Component\Application\User\UseCase\CreateUserUseCase
        arguments:
            - '@letemtalk.repository.user'

    letemtalk.usecase.readusers:
        class: LetEmTalk\Component\Application\User\UseCase\ReadUsersUseCase
        arguments:
            - '@letemtalk.repository.user'

    letemtalk.usecase.deleteuser:
        class: LetEmTalk\Component\Application\User\UseCase\DeleteUserUseCase
        arguments:
            - '@letemtalk.repository.user'

    letemtalk.usercase.createusercredentials:
        class: LetEmTalk\Component\ApiLet\Application\Authentication\UserCase\CreateUserCredentialsUseCase
        arguments:
            - '@letemtalk.repository.usercredentials'